# Generated by Django 5.0.4 on 2024-04-20 16:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DishTag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=32)),
                ("location", models.CharField(max_length=32)),
                ("phone_number", models.CharField(max_length=11)),
                ("description", models.CharField(max_length=150, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="images")),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[("id", models.AutoField(primary_key=True, serialize=False)),],
        ),
        migrations.CreateModel(
            name="Dish",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=32)),
                ("description", models.CharField(max_length=150, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="images")),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("tags", models.ManyToManyField(to="tjeatwhatApp.dishtag")),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tjeatwhatApp.restaurant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DishEval",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "score",
                    models.SmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.CharField(max_length=200)),
                ("time", models.DateTimeField()),
                ("reply", models.CharField(max_length=200)),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tjeatwhatApp.dish",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tjeatwhatApp.user",
                    ),
                ),
            ],
        ),
    ]
