# Generated by Django 5.0.4 on 2024-05-10 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tjeatwhatApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='ip',
        ),
    ]
