# Generated by Django 5.0.4 on 2024-04-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tjeatwhatApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(1, '绿牌'), (2, '蓝牌'), (3, '黄牌')], default=1, verbose_name='牌子'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
