# Generated by Django 5.0.5 on 2024-05-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tjeatwhatApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='time',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
