# Generated by Django 5.0.4 on 2024-05-08 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tjeatwhatApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tjeatwhatApp.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tjeatwhatApp.users')),
            ],
        ),
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tjeatwhatApp.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tjeatwhatApp.users')),
            ],
        ),
    ]
