# Generated by Django 5.0.5 on 2024-05-28 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tjeatwhatApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restimage',
            name='image',
            field=models.ImageField(blank=True, default='images/default_image.jpg', null=True, upload_to='images'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.IntegerField(default=0)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='tjeatwhatApp.user')),
                ('replier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replier', to='tjeatwhatApp.user')),
            ],
        ),
    ]
