# Generated by Django 5.0.5 on 2024-05-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tjeatwhatApp', '0002_alter_restimage_image_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(1, '绿牌'), (2, '蓝牌'), (3, '黄牌')], default=1, verbose_name='激活状态'),
        ),
    ]
