# Generated by Django 5.0.4 on 2024-05-08 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tjeatwhatApp', '0002_star_upvote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='PostImages',
        ),
    ]
