# Generated by Django 5.0.4 on 2024-04-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tjeatwhatApp', '0002_user_status_alter_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
