# Generated by Django 5.0.4 on 2024-04-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tjeatwhatApp', '0003_alter_user_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.IntegerField(choices=[(1, '绿牌'), (2, '蓝牌'), (3, '黄牌')], default=1, verbose_name='牌子'),
        ),
    ]
