# Generated by Django 5.0.5 on 2024-05-11 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tjeatwhatApp', '0003_remove_dish_tags_alter_resttag_name_delete_dishtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disheval',
            name='reply_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='disheval',
            name='time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='restimage',
            name='image',
            field=models.ImageField(blank=True, default='images/test.jpg', null=True, upload_to='images'),
        ),
    ]
