# Generated by Django 5.0.4 on 2024-05-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tjeatwhatApp', '0003_rename_images_postimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
